// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from "@prisma-next/adapter-postgres/operation-types";
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma-next/target-postgres/codec-types";
import type { CodecTypes as LtreeTypes, Ltree } from "prisma-ltree/codec-types";
import type { QueryOperationTypes as LtreeQueryOperationTypes } from "prisma-ltree/operation-types";

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from "@prisma-next/sql-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma-next/contract/types";

export type StorageHash =
  StorageHashBase<"sha256:3598d200521bad542c32c8cdb6d5c2adbe0be4f092857b12dbe5aa2faff59f31">;
export type ExecutionHash =
  ExecutionHashBase<"sha256:2eab8e74aa05b3a48a9d465f18981c505d28cf4fe434a88901d95fc416f32cc2">;
export type ProfileHash =
  ProfileHashBase<"sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb">;

export type CodecTypes = PgTypes & LtreeTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes> &
  LtreeQueryOperationTypes<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]["output"]
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Taxon: {
      readonly id: Char<36>;
      readonly path: CodecTypes["pg/ltree@1"]["output"];
      readonly scientificName: CodecTypes["pg/text@1"]["output"];
      readonly commonName: CodecTypes["pg/text@1"]["output"] | null;
      readonly rank: CodecTypes["pg/text@1"]["output"];
      readonly extinct: CodecTypes["pg/bool@1"]["output"];
      readonly maOrigin: CodecTypes["pg/float8@1"]["output"] | null;
      readonly maExtinct: CodecTypes["pg/float8@1"]["output"] | null;
      readonly wikiUrl: CodecTypes["pg/text@1"]["output"];
      readonly thumbnailUrl: CodecTypes["pg/text@1"]["output"] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Taxon: {
      readonly id: CodecTypes["sql/char@1"]["input"];
      readonly path: CodecTypes["pg/ltree@1"]["input"];
      readonly scientificName: CodecTypes["pg/text@1"]["input"];
      readonly commonName: CodecTypes["pg/text@1"]["input"] | null;
      readonly rank: CodecTypes["pg/text@1"]["input"];
      readonly extinct: CodecTypes["pg/bool@1"]["input"];
      readonly maOrigin: CodecTypes["pg/float8@1"]["input"] | null;
      readonly maExtinct: CodecTypes["pg/float8@1"]["input"] | null;
      readonly wikiUrl: CodecTypes["pg/text@1"]["input"];
      readonly thumbnailUrl: CodecTypes["pg/text@1"]["input"] | null;
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly taxon: {
              columns: {
                readonly id: {
                  readonly nativeType: "character";
                  readonly codecId: "sql/char@1";
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly path: {
                  readonly nativeType: "ltree";
                  readonly codecId: "pg/ltree@1";
                  readonly nullable: false;
                  readonly typeRef: "Path";
                };
                readonly scientific_name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly common_name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly rank: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly extinct: {
                  readonly nativeType: "bool";
                  readonly codecId: "pg/bool@1";
                  readonly nullable: false;
                };
                readonly ma_origin: {
                  readonly nativeType: "float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: true;
                };
                readonly ma_extinct: {
                  readonly nativeType: "float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: true;
                };
                readonly wiki_url: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly thumbnail_url: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["path"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly types: {
      readonly Path: {
        readonly kind: "codec-instance";
        readonly codecId: "pg/ltree@1";
        readonly nativeType: "ltree";
        readonly typeParams: Record<string, never>;
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly taxon: { readonly namespace: "public" & NamespaceId; readonly model: "Taxon" };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Taxon: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "sql/char@1";
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly path: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/ltree@1" };
              };
              readonly scientificName: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly commonName: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly rank: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly extinct: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
              };
              readonly maOrigin: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/float8@1" };
              };
              readonly maExtinct: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/float8@1" };
              };
              readonly wikiUrl: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly thumbnailUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "taxon";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly path: { readonly column: "path" };
                readonly scientificName: { readonly column: "scientific_name" };
                readonly commonName: { readonly column: "common_name" };
                readonly rank: { readonly column: "rank" };
                readonly extinct: { readonly column: "extinct" };
                readonly maOrigin: { readonly column: "ma_origin" };
                readonly maExtinct: { readonly column: "ma_extinct" };
                readonly wikiUrl: { readonly column: "wiki_url" };
                readonly thumbnailUrl: { readonly column: "thumbnail_url" };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly "ltree.path": true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {
    readonly ltree: {
      readonly capabilities: { readonly postgres: { readonly "ltree.path": true } };
      readonly familyId: "sql";
      readonly id: "ltree";
      readonly kind: "extension";
      readonly targetId: "postgres";
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: "LtreeTypes";
            readonly named: "CodecTypes";
            readonly package: "prisma-ltree/codec-types";
          };
          readonly typeImports: readonly [
            {
              readonly alias: "Ltree";
              readonly named: "Ltree";
              readonly package: "prisma-ltree/codec-types";
            },
          ];
        };
        readonly queryOperationTypes: {
          readonly import: {
            readonly alias: "LtreeQueryOperationTypes";
            readonly named: "QueryOperationTypes";
            readonly package: "prisma-ltree/operation-types";
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: "sql";
            readonly nativeType: "ltree";
            readonly targetId: "postgres";
            readonly typeId: "pg/ltree@1";
          },
          {
            readonly familyId: "sql";
            readonly nativeType: "ltree[]";
            readonly targetId: "postgres";
            readonly typeId: "pg/ltree-array@1";
          },
        ];
      };
      readonly version: "0.1.0";
    };
  };
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "taxon";
            readonly column: "id";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv4" };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
