packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  alchemy: 2.0.0-beta.56
  effect: 4.0.0-beta.84
  '@effect/platform-bun': 4.0.0-beta.84
  '@effect/platform-node': 4.0.0-beta.84
  tslib: ^2.8.1
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
    '@distilled.cloud/cloudflare': "*"
allowBuilds:
  '@parcel/watcher': true
  msgpackr-extract: true
  unrs-resolver: true
  workerd: true
