packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
  vite-plus: 0.1.24
  "@electric-sql/pglite": ^0.5.3
  alchemy: 2.0.0-beta.57
  effect: 4.0.0-beta.84
  "@effect/platform-bun": 4.0.0-beta.84
  "@effect/platform-node": 4.0.0-beta.84
  tslib: ^2.8.1
  "@vitest/coverage-v8": 4.1.9
  shiki: ^4.2.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
    "@distilled.cloud/cloudflare": "*"
allowBuilds:
  esbuild: true
  "@parcel/watcher": true
  msgpackr-extract: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - "@distilled.cloud/aws@0.26.1"
  - "@distilled.cloud/axiom@0.26.1"
  - "@distilled.cloud/cloudflare@0.26.1"
  - "@distilled.cloud/core@0.26.1"
  - "@distilled.cloud/neon@0.26.1"
  - "@distilled.cloud/planetscale@0.26.1"
  - alchemy@2.0.0-beta.57
